# Generated by Django 4.1.5 on 2023-01-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
